[workspace]
members = ["projects/*"]
default-members = [
    "projects/tailwind-to-css",
    "projects/tailwind-cli",
    "projects/tailwind-rs",
]
exclude = [
    "projects/.DS_Store",
]


[profile.dev]
opt-level = 1
incremental = true

[profile.release]
lto = true
panic = "abort"
